[package]
name = "utility-stats"
version = "0.1.0"
authors = ["Chris Lieb <chris.lieb@gmail.com>"]
edition = "2018"

[dependencies]
clap = "~2.33"
csv = "~1.1"
flate2 = "~1.0"
log = "~0.4"
reqwest = { version="~0.10", features=["blocking", "gzip", "json"] }
rmp-serde = "~0.14"
rusqlite = { version="~0.24", features=["bundled"] }
serde = "~1.0"
serde_derive = "~1.0"
serde_json = "~1.0"
simplelog = "~0.8"
time = "~0.2"
