[package]
name = "utility-stats"
version = "0.1.0"
authors = ["Chris Lieb <chris.lieb@gmail.com>"]
edition = "2018"
resolver = "2"

[dependencies]
clap = "~2.33"
csv = "~1.1"
flate2 = "~1.0"
log = "~0.4"
reqwest = { version="~0.11", features=["blocking", "gzip", "json"] }
rmp-serde = "~0.15"
rusqlite = { version="~0.25", features=["bundled"] }
serde = { version = "~1.0", features = [ "derive" ] }
serde_json = "~1.0"
simplelog = "~0.10"
time = "~0.2"
