[package]
name = "utility-stats"
version = "0.1.0"
authors = ["Chris Lieb <chris.lieb@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "~0.4"
clap = "~2.32"
csv = "~1.0"
log = "~0.4"
reqwest = "~0.9"
serde = "~1.0"
serde_derive = "~1.0"
serde_json = "~1.0"
simplelog = "~0.5"
time = "~0.1"
